# Learn more about filters
# https://api-platform.com/docs/core/filters
services:
    item.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments:
            -
                id: 'exact'
                query: 'partial'
                # Taxonomies.
                subjects: ~
                recommenders: ~
                contexts: ~
                audiences: ~
        tags: ['api_platform.filter']

    item.range_filter:
        parent: 'api_platform.doctrine.orm.range_filter'
        arguments: [ { duration: ~ } ]
        tags: ['api_platform.filter']

    item.published_filter:
        class: AppBundle\Filter\PublishedFilter
        arguments:
            - '@doctrine'
            - '@request_stack'
        tags: ['api_platform.filter']
