# Learn more about filters
# https://api-platform.com/docs/core/filters
services:
    item.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments:
            -
                id: 'exact'
                query: 'partial'
                # Taxonomies.
                subjects: ~
                recommenders: ~
                contexts: ~
                audiences: ~
                categories: ~
                relatedMaterials: ~
        tags: ['api_platform.filter']

    item.range_filter:
        parent: AppBundle\Filter\DurationFilter
        arguments:
            - '@doctrine'
            - '@request_stack'
            - '@?logger'
            -
                duration: ~
        tags: ['api_platform.filter']

    item.geolocation_filter:
        parent: AppBundle\Filter\GeolocationFilter
        arguments:
            - '@doctrine'
            - '@request_stack'
            - '@?logger'
            -
                property: geolocation
                alias: geolocation
                lat: latitude
                lng: longitude
        tags: ['api_platform.filter']

    item.published_filter:
        class: AppBundle\Filter\PublishedFilter
        arguments:
            - '@doctrine'
            - '@request_stack'
        tags: ['api_platform.filter']

    collection.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments:
            -
                id: 'exact'
                title: 'partial'
                description: 'partial'
        tags: ['api_platform.filter']

    collection.published_filter:
        class: AppBundle\Filter\PublishedFilter
        arguments:
            - '@doctrine'
            - '@request_stack'
        tags: ['api_platform.filter']
