imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver: 'pdo_sqlite'
        path: '%kernel.cache_dir%/db.sqlite'
        charset: 'UTF8'

services:
    # For some reason, this service is not autoloaded in the "test" environment.
    AppBundle\Service\FeedReader:
        arguments:
            - '@AppBundle\Service\Helper'
        public: true
