easy_admin:
    site_name: '%site_name%'

    entities:
        Item:
            class: AppBundle\Entity\Item
            disabled_actions: [delete, new]
            list:
                fields:
                    - property: title
                    - property: updatedAt
                    - property: publishedAt
                    - property: tags
                      template: tags.html.twig
                    - property: feed

            edit:
                fields:
                    - type: group
                      css_class: 'custom-information'
                      label: 'Custom information'
                    - property: publishedAt

                    - type: group
                      css_class: 'basic-information'
                      label: 'Basic information'
                    - property: title
                      type_options:
                          disabled: true
                          required: false
                    - property: tags
                      label: Categories
                      type_options:
                          disabled: true
                          required: false


        Feed:
            class: AppBundle\Entity\Feed
            disabled_actions: [delete]
            list:
                fields:
                    - property: title
                    - property: url
                      type: url
                    - property: enabled
                      type: boolean
                    - property: lastReadAt
                    - property: ttl
                      sortable: false

            form:
                fields:
                    - property: enabled
                    - property: title
                    - property: url
                      type: url


        # Tag:
        #     class: AppBundle\Entity\Tag
        #     list:
        #         fields:
        #             - property: name
        #             - property: slug

        #     form:
        #         fields:
        #             - property: name


        User:
            class: AppBundle\Entity\User
            list:
                fields:
                    - property: email
                    - property: roles
                    - property: last_login
                      type: datetime

            form:
                fields:
                    - property: email
                      type: email
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices: &role_list
                              ROLE_USER: ROLE_USER
                              ROLE_ADMIN: ROLE_ADMIN
