easy_admin:
    site_name: '%site_name%'
    design:
        form_theme: 'easy_admin/form/bootstrap_3_horizontal_layout.html.twig'
        assets:
            js:
                - 'assets/js/easyadmin.js'

        menu:
            - Item
            - { label: 'Taxonomy' }
            - Subject
            - Recommender
            - Context
            - Audience
            - { label: 'Admin' }
            - Feed
            - User


    entities:
        Item:
            class: AppBundle\Entity\Item
            disabled_actions: [delete, new]
            list:
                fields:
                    - property: title
                    - property: updatedAt
                    - property: publishedAt
                    - property: subjects
                      template: subjects.html.twig
                    - property: feed

            edit:
                fields:
                    - type: group
                      css_class: 'custom-information'
                      label: 'Custom information'
                    - property: publishedAt
                      type_options:
                          view_timezone: "%view_timezone%"
                          widget: single_text
                          html5: true
                    - property: subjects
                    - property: recommenders
                    - property: contexts
                    - property: audiences
                    - property: latitude
                    - property: longitude


        Feed:
            class: AppBundle\Entity\Feed
            disabled_actions: [delete]
            list:
                fields:
                    - property: title
                    - property: url
                      type: url
                    - property: enabled
                      type: boolean
                    - property: lastReadAt
                    - property: ttl
                      sortable: false

            form:
                fields:
                    - property: enabled
                    - property: title
                    - property: url
                      type: url


        Subject:
            class: AppBundle\Entity\Taxonomy\Subject
            list:
                fields:
                    - property: name
                    - property: slug

            form:
                fields:
                    - property: name

        Recommender:
            class: AppBundle\Entity\Taxonomy\Recommender
            list:
                fields:
                    - property: name
                    - property: slug

            form:
                fields:
                    - property: name

        Context:
            class: AppBundle\Entity\Taxonomy\Context
            list:
                fields:
                    - property: name
                    - property: slug

            form:
                fields:
                    - property: name

        Audience:
            class: AppBundle\Entity\Taxonomy\Audience
            list:
                fields:
                    - property: name
                    - property: slug

            form:
                fields:
                    - property: name

        User:
            class: AppBundle\Entity\User
            list:
                fields:
                    - property: email
                    - property: roles
                    - property: last_login
                      type: datetime

            form:
                fields:
                    - property: email
                      type: email
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices: &role_list
                              ROLE_USER: ROLE_USER
                              ROLE_ADMIN: ROLE_ADMIN
