easy_admin:
    entities:
        Item:
            class: AppBundle\Entity\Item
            disabled_actions: [delete, new]
            list:
                fields:
                    - property: title
                    - property: updatedAt
                    - property: publishedAt
                    - property: tags
                      template: tags.html.twig

            edit:
                fields:
                    - type: group
                      css_class: 'custom-information'
                      label: 'Custom information'
                    - property: publishedAt

                    - type: group
                      css_class: 'basic-information'
                      label: 'Basic information'
                    - property: title
                      type_options:
                          disabled: true
                          required: false
                    - property: tags
                      type: easyadmin_autocomplete
                      type_options:
                          multiple: true
                          class: AppBundle\Entity\Tag
                          required: false
                          disabled: true


        Feed:
            class: AppBundle\Entity\Feed
            disabled_actions: [delete]
            list:
                fields:
                    - property: title
                    - property: url
                      type: url
                    - property: enabled
                      type: boolean
                    - property: lastReadAt
                    - property: ttl
                      sortable: false

            edit:
                fields:
                    - property: enabled
                    - property: title
                    - property: url
                      type: url


        Tag:
            class: AppBundle\Entity\Tag
