easy_admin:
    entities:
        Item:
            class: AppBundle\Entity\Item
            disabled_actions: [new]
            list:
                fields:
                    - property: title
                    - property: tags
                      template: tags.html.twig

            edit:
                fields:
                    - type: group
                      css_class: 'basic-information'
                      label: 'Basic information'
                    - property: title
                      type_options:
                          disabled: true
                          required: false
                    - property: tags
                      type: easyadmin_autocomplete
                      type_options:
                          multiple: true
                          class: AppBundle\Entity\Tag
                          required: false
                          disabled: true


        Feed:
            class: AppBundle\Entity\Feed
            list:
                fields:
                    - property: title
                    - property: url
                      type: url

            edit:
                fields:
                    - property: title
                    - property: url
                      type: url


        Tag:
            class: AppBundle\Entity\Tag
