api:
    resource: '.'
    type: 'api_platform'
    prefix: /api

app:
    resource: '@AppBundle/Action/'
    type: 'annotation'

easy_admin_bundle:
    resource: '@AppBundle/Controller/AdminController.php'
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
