#!/usr/bin/env bash
dir=$(cd $(dirname "${BASH_SOURCE[0]}")/../ && pwd)

cd $dir

env=${1:-dev}

rm -fr var/{cache,sessions}/*/*
mkdir -p var/{cache,logs,sessions}/$env

if [ "$env" == "prod" ]; then
    # rm web/app_{acceptance,dev}.php web/config.php
    SYMFONY_ENV=$env composer install --no-dev --optimize-autoloader
else
    SYMFONY_ENV=$env composer install
fi
SYMFONY_ENV=$env bin/console assets:install --symlink
SYMFONY_ENV=$env bin/console cache:clear --no-warmup
SYMFONY_ENV=$env bin/console cache:warmup
SYMFONY_ENV=$env bin/console doctrine:migrations:migrate --no-interaction
